### ISSUE TITLE
show 'object not found'

### ISSUE THREAD

**Issue by arafatkazi19** [sangit0/Stock-Management#2]
When I want to add new supplier it redirects to 'http://localhost/save-supplyer' page and shows 'object not found' page. What's the solution of this??

**Comment by sangit0** [comment]
I guess it's due to xampp. Can you please check the configuration?

**Comment by arafatkazi19** [comment]
Thanks for the quick reply !! 
Issue solved. It was due to the naming of the routes in form tag!!
